name: ymir

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - caddy-config:/config
      - caddy-data:/data

  api:
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB=${DB}
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 40s
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  caddy-config:
  caddy-data:
  db-data:
